import uuid from 'uuid';

import runningOnEmpty from './images/runningOnEmpty.jpg';
import ordinaryPeople from './images/ordinaryPeople.jpg';
import breakingAway from './images/breakingAway.jpg';
import saturdayNightFever from './images/saturdayNightFever.jpg';
import riskyBusiness from './images/riskyBusiness.jpg';
import clueless from './images/clueless.jpg';
import murmurOfTheHeart from './images/murmurOfTheHeart.jpg';
import carrie from './images/carrie.jpg';
import dazedAndConfused from './images/dazedAndConfused.jpg';
import squidAndTheWhale from './images/squidAndTheWhale.jpg';
import sevenSamurai from './images/sevenSamurai.jpg';
import eightHalf from './images/8half.jpg';
import redShoes from './images/redShoes.jpg';
import mulhollandDrive from './images/mulhollandDrive.jpg';
import annieHall from './images/annieHall.jpg';
import dogtooth from './images/dogtooth2.jpg';
import fireWalkWithMe from './images/fireWalkWithMe.jpg';
import casablanca from './images/casablanca.jpg';
import rebecca from './images/rebecca.jpg';
import moonlight from './images/moonlight.jpg';
import theApartment from './images/theApartment.jpg';
import amadeus from './images/amadeus.jpg';
import vanillaSky from './images/vanillaSky.jpg';
import fromHereToEternity from './images/fromHereToEternity.jpg';
import fannyAndAlexander from './images/fannyAndAlexander.jpg';
import rocky from './images/rocky.jpg';
import threeWomen from './images/threeWomen.jpg';
import planetOfTheApes from './images/planetOfTheApes.jpg';
import julesEtJim from './images/julesEtJim.jpg';
import masculinFeminin from './images/masculinFeminin.jpg';
import persona from './images/persona.jpg';
import ran from './images/ran.jpg';
import marienbad from './images/lastYearAtMarienbad.jpg';
import vertigo from './images/vertigo.jpg';
import womanInTheDunes from './images/womanInTheDunes.jpg';
import mistressAmerica from './images/mistressAmerica.jpg';
import margotAtTheWedding from './images/margotAtTheWedding.jpg';
import greenberg from './images/greenberg.jpg';
import whileWeWereYoung from './images/whileWeWereYoung.jpg';
import theMeyerowitzStories from './images/theMeyerowitzStories.jpg';
import francesHa from './images/francesHa.jpg';
import kickingAndScreaming from './images/kickingAndScreaming.jpeg';
import apocalypseNow from './images/apocalypseNow.jpg';
import theConversation from './images/theConversation.jpg';
import pulpFiction from './images/pulpFiction.jpg';
import parisTexas from './images/parisTexas.jpg';
import missJulie from './images/missJulie.jpg';
import taxiDriver from './images/taxiDriver.jpg';
import newYorkNewYork from './images/newYorkNewYork.jpg';
import dancerInTheDark from './images/dancerInTheDark.jpg';
import kingOfComedy from './images/kingOfComedy.jpg';
import ifEllipsis from './images/ifEllipsis.jpg';
import meanStreets from './images/meanStreets.jpg';
import casino from './images/casino.jpg';
import wagesOfFear from './images/wagesOfFear.jpg';
import goodfellas from './images/goodfellas.jpg';
import allThatJazz from './images/allThatJazz.jpg';
import kagemusha from './images/kagemusha.jpg';
import thereWillBeBlood from './images/thereWillBeBlood.jpg';
import fishTank from './images/fishTank.jpg';

const filmData = [
  {
    title: 'Running on Empty',
    duration: '116 minutes',
    year: 1988,
    genre: ['I GUESS THIS IS GROWING UP'],
    director: 'Sidney Lumet',
    actors: ['River Phoenix, Christine Lahti, Judd Hirsch'],
    img: runningOnEmpty,
    id: uuid.v4(),
    addedToMyList: false,
    isVisibleToSlider: false,
    isLeftMostSlide: false,
    isRightMostSlide: false,
  },
  {
    title: 'Ordinary People',
    duration: '124 minutes',
    year: 1980,
    genre: ['I GUESS THIS IS GROWING UP'],
    director: 'Robert Redford',
    actors: [' Donald Sutherland, Mary Tyler Moore, Judd Hirsch'],
    img: ordinaryPeople,
    id: uuid.v4(),
    addedToMyList: false,
    isVisibleToSlider: false,
    isLeftMostSlide: false,
    isRightMostSlide: false,
  },
  {
    title: 'Breaking Away',
    duration: '101 minutes',
    year: 1979,
    genre: ['I GUESS THIS IS GROWING UP'],
    director: 'Peter Yates',
    actors: [' Dennis Christopher, Dennis Quaid, Daniel Stern'],
    img: breakingAway,
    id: uuid.v4(),
    addedToMyList: false,
    isVisibleToSlider: false,
    isLeftMostSlide: false,
    isRightMostSlide: false,
  },
  {
    title: 'Saturday Night Fever',
    duration: '118 minutes',
    year: 1977,
    genre: ['I GUESS THIS IS GROWING UP'],
    director: 'John Badham',
    actors: ['John Travolta, Karen Lynn Gorney, Barry Miller'],
    img: saturdayNightFever,
    id: uuid.v4(),
    addedToMyList: false,
    isVisibleToSlider: false,
    isLeftMostSlide: false,
    isRightMostSlide: false,
  },
  {
    title: 'Risky Business',
    duration: '99 minutes',
    year: 1983,
    genre: ['I GUESS THIS IS GROWING UP'],
    director: 'Paul Brickman',
    actors: ['Tom Cruise, Rebecca De Mornay, Joe Pantoliano'],
    img: riskyBusiness,
    id: uuid.v4(),
    addedToMyList: false,
    isVisibleToSlider: false,
    isLeftMostSlide: false,
    isRightMostSlide: false,
  },
  {
    title: 'Clueless',
    duration: '97 minutes',
    year: 1995,
    genre: ['I GUESS THIS IS GROWING UP'],
    director: 'Amy Heckerling',
    actors: ['Alicia Silverstone, Stacey Dash, Brittany Murphy'],
    img: clueless,
    id: uuid.v4(),
    addedToMyList: false,
    isVisibleToSlider: false,
    isLeftMostSlide: false,
    isRightMostSlide: false,
  },
  {
    title: 'Murmur of the Heart',
    duration: '118 minutes',
    year: 1971,
    genre: ['I GUESS THIS IS GROWING UP'],
    director: 'Louis Malle',
    actors: ['Lea Massari, Benoît Ferreux, Daniel Gélin'],
    img: murmurOfTheHeart,
    id: uuid.v4(),
    addedToMyList: false,
    isVisibleToSlider: false,
    isLeftMostSlide: false,
    isRightMostSlide: false,
  },
  {
    title: 'Carrie',
    duration: '98 minutes',
    year: 1976,
    genre: ['I GUESS THIS IS GROWING UP'],
    director: 'Brian De Palma',
    actors: ['Sissy Spacek, Piper Laurie, Amy Irving'],
    img: carrie,
    id: uuid.v4(),
    addedToMyList: false,
    isVisibleToSlider: false,
    isLeftMostSlide: false,
    isRightMostSlide: false,
  },
  {
    title: 'Dazed and Confused',
    duration: '102 minutes',
    year: 1993,
    genre: ['I GUESS THIS IS GROWING UP'],
    director: 'Richard Linklater',
    actors: ['Jason London, Wiley Wiggins, Matthew McConaughey'],
    img: dazedAndConfused,
    id: uuid.v4(),
    addedToMyList: false,
    isVisibleToSlider: false,
    isLeftMostSlide: false,
    isRightMostSlide: false,
  },
  {
    title: 'The Squid and the Whale',
    duration: '81 minutes',
    year: 2005,
    genre: ['I GUESS THIS IS GROWING UP', 'DIRECTED BY NOAH BAUMBACH'],
    director: 'Noah Baumbach',
    actors: ['Owen Kline, Jeff Daniels, Laura Linney'],
    img: squidAndTheWhale,
    id: uuid.v4(),
    addedToMyList: false,
    isVisibleToSlider: false,
    isLeftMostSlide: false,
    isRightMostSlide: false,
  },
  {
    title: '8½',
    duration: '138 minutes',
    year: 1963,
    genre: ['ESSENTIAL ART-HOUSE'],
    director: 'Federico Fellini',
    actors: ['Marcello Mastroianni', 'Anouk Aimée', 'Claudia Cardinale'],
    img: eightHalf,
    id: uuid.v4(),
    addedToMyList: false,
    isVisibleToSlider: false,
    isLeftMostSlide: false,
    isRightMostSlide: false,
  },
  {
    title: 'Fanny and Alexander',
    duration: '178 minutes',
    year: 1982,
    genre: ['ESSENTIAL ART-HOUSE'],
    director: 'Ingmar Bergman',
    actors: ['Bertil Guve, Pernilla Allwin, Kristina Adolphson'],
    img: fannyAndAlexander,
    id: uuid.v4(),
    addedToMyList: false,
    isVisibleToSlider: false,
    isLeftMostSlide: false,
    isRightMostSlide: false,
  },
  {
    title: 'Woman in the Dunes',
    duration: '123 minutes',
    year: 1964,
    genre: ['ESSENTIAL ART-HOUSE'],
    director: 'Hiroshi Teshigahara',
    actors: ['Eiji Okada, Kyôko Kishida, Hiroko Itô'],
    img: womanInTheDunes,
    id: uuid.v4(),
    addedToMyList: false,
    isVisibleToSlider: false,
    isLeftMostSlide: false,
    isRightMostSlide: false,
  },
  {
    title: 'The Red Shoes',
    duration: '134 minutes',
    year: 1948,
    genre: ['ESSENTIAL ART-HOUSE'],
    director: 'Michael Powell and Emeric Pressburger',
    actors: ['Anton Walbrook, Marius Goring, Moira Shearer'],
    img: redShoes,
    id: uuid.v4(),
    addedToMyList: false,
    isVisibleToSlider: false,
    isLeftMostSlide: false,
    isRightMostSlide: false,
  },
  {
    title: 'Ran',
    duration: ' minutes',
    year: 1985,
    genre: ['ESSENTIAL ART-HOUSE'],
    director: 'Akira Kurosawa',
    actors: ['Tatsuya Nakadai, Akira Terao, Jinpachi Nezu '],
    img: ran,
    id: uuid.v4(),
    addedToMyList: false,
    isVisibleToSlider: false,
    isLeftMostSlide: false,
    isRightMostSlide: false,
  },
  {
    title: 'Vertigo',
    duration: '128 minutes',
    year: 1958,
    genre: ['ESSENTIAL ART-HOUSE'],
    director: 'Alfred Hitchcock',
    actors: ['James Stewart, Kim Novak, Barbara Bel Geddes'],
    img: vertigo,
    id: uuid.v4(),
    addedToMyList: false,
    isVisibleToSlider: false,
    isLeftMostSlide: false,
    isRightMostSlide: false,
  },
  {
    title: 'Jules et Jim',
    duration: '105 minutes',
    year: 1962,
    genre: ['ESSENTIAL ART-HOUSE'],
    director: 'Francois Truffaut',
    actors: ['Jeanne Moreau, Oskar Werner, Henri Serre'],
    img: julesEtJim,
    id: uuid.v4(),
    addedToMyList: false,
    isVisibleToSlider: false,
    isLeftMostSlide: false,
    isRightMostSlide: false,
  },
  {
    title: 'Masculin Féminin',
    duration: '103 minutes',
    genre: ['ESSENTIAL ART-HOUSE'],
    year: 1966,
    director: 'Jean-Luc Godard',
    actors: ['Jean-Pierre Léaud, Chantal Goya, Marlène Jobert'],
    img: masculinFeminin,
    id: uuid.v4(),
    addedToMyList: false,
    isVisibleToSlider: false,
    isLeftMostSlide: false,
    isRightMostSlide: false,
  },
  {
    title: 'Seven Samurai',
    duration: '307 minutes',
    year: 1954,
    genre: ['ESSENTIAL ART-HOUSE'],
    director: 'Akira Kurosawa',
    actors: ['Toshirô Mifune, Takashi Shimura, Keiko Tsushima'],
    img: sevenSamurai,
    id: uuid.v4(),
    addedToMyList: false,
    isVisibleToSlider: false,
    isLeftMostSlide: false,
    isRightMostSlide: false,
  },
  {
    title: 'Persona',
    duration: '83 minutes',
    year: 1966,
    genre: ['SOMETHING WEIRD IS GOING ON'],
    director: 'Ingmar Bergman',
    actors: ['Bibi Andersson, Liv Ullmann, Margaretha Krook'],
    img: persona,
    id: uuid.v4(),
    addedToMyList: false,
    isVisibleToSlider: false,
    isLeftMostSlide: false,
    isRightMostSlide: false,
  },
  {
    title: 'Last Year at Marienbad',
    duration: '94 minutes',
    year: 1961,
    genre: ['SOMETHING WEIRD IS GOING ON'],
    director: 'Alain Resnais',
    actors: ['Delphine Seyrig, Giorgio Albertazzi, Sacha Pitoëff '],
    img: marienbad,
    id: uuid.v4(),
    addedToMyList: false,
    isVisibleToSlider: false,
    isLeftMostSlide: false,
    isRightMostSlide: false,
  },
  {
    title: 'Twin Peaks: Fire Walk with Me',
    duration: '134 minutes',
    year: 1992,
    genre: ['SOMETHING WEIRD IS GOING ON'],
    director: 'David Lynch',
    actors: ['Sheryl Lee, Ray Wise, Mädchen Amick'],
    img: fireWalkWithMe,
    id: uuid.v4(),
    addedToMyList: false,
    isVisibleToSlider: false,
    isLeftMostSlide: false,
    isRightMostSlide: false,
  },
  {
    title: 'Dogtooth',
    duration: '97 minutes',
    year: 2009,
    genre: ['SOMETHING WEIRD IS GOING ON'],
    director: 'Yorgos Lanthimos',
    actors: ['Christos Stergioglou, Michele Valley, Angeliki Papoulia'],
    img: dogtooth,
    id: uuid.v4(),
    addedToMyList: false,
    isVisibleToSlider: false,
    isLeftMostSlide: false,
    isRightMostSlide: false,
  },
  {
    title: 'Mulholland Drive',
    duration: '147 minutes',
    year: 2001,
    genre: ['SOMETHING WEIRD IS GOING ON'],
    director: 'David Lynch',
    actors: ['Naomi Watts, Laura Harring, Justin Theroux'],
    img: mulhollandDrive,
    id: uuid.v4(),
    addedToMyList: false,
    isVisibleToSlider: false,
    isLeftMostSlide: false,
    isRightMostSlide: false,
  },
  {
    title: '3 Women',
    duration: '127 minutes',
    year: 1977,
    genre: ['SOMETHING WEIRD IS GOING ON'],
    director: 'Robert Altman',
    actors: ['Shelley Duvall, Sissy Spacek, Janice Rule'],
    img: threeWomen,
    id: uuid.v4(),
    addedToMyList: false,
    isVisibleToSlider: false,
    isLeftMostSlide: false,
    isRightMostSlide: false,
  },
  {
    title: 'Planet of the Apes',
    duration: '112 minutes',
    year: 1969,
    genre: ['SOMETHING WEIRD IS GOING ON'],
    director: 'Franklin J. Schaffner',
    actors: ['Charlton Heston, Roddy McDowall, Kim Hunter'],
    img: planetOfTheApes,
    id: uuid.v4(),
    addedToMyList: false,
    isVisibleToSlider: false,
    isLeftMostSlide: false,
    isRightMostSlide: false,
  },
  {
    title: 'Vanilla Sky',
    duration: '136 minutes',
    year: 2001,
    genre: ['SOMETHING WEIRD IS GOING ON'],
    director: 'Cameron Crowe',
    actors: ['Tom Cruise, Penélope Cruz, Cameron Diaz'],
    img: vanillaSky,
    id: uuid.v4(),
    addedToMyList: false,
    isVisibleToSlider: false,
    isLeftMostSlide: false,
    isRightMostSlide: false,
  },
  {
    title: 'Rebecca',
    duration: '130 minutes',
    year: 1940,
    genre: ['OSCAR WINNERS THAT ARE ACTUALLY GOOD'],
    director: 'Alfred Hitchcock',
    actors: ['Laurence Olivier, Joan Fontaine, George Sanders'],
    img: rebecca,
    id: uuid.v4(),
    addedToMyList: false,
    isVisibleToSlider: false,
    isLeftMostSlide: false,
    isRightMostSlide: false,
  },
  {
    title: 'Casablanca',
    duration: '102 minutes',
    year: 1942,
    genre: ['OSCAR WINNERS THAT ARE ACTUALLY GOOD'],
    director: 'Michael Curtiz',
    actors: ['Humphrey Bogart, Ingrid Bergman, Paul Henreid'],
    img: casablanca,
    id: uuid.v4(),
    addedToMyList: false,
    isVisibleToSlider: false,
    isLeftMostSlide: false,
    isRightMostSlide: false,
  },
  {
    title: 'Moonlight',
    duration: '111 minutes',
    year: 2016,
    genre: ['OSCAR WINNERS THAT ARE ACTUALLY GOOD'],
    director: 'Barry Jenkins',
    actors: ['Mahershala Ali, Naomie Harris, Trevante Rhodes'],
    img: moonlight,
    id: uuid.v4(),
    addedToMyList: false,
    isVisibleToSlider: false,
    isLeftMostSlide: false,
    isRightMostSlide: false,
  },
  {
    title: 'Rocky',
    duration: '120 minutes',
    year: 1976,
    genre: ['OSCAR WINNERS THAT ARE ACTUALLY GOOD'],
    director: 'John G. Avildsen',
    actors: ['Sylvester Stallone, Talia Shire, Burt Young'],
    img: rocky,
    id: uuid.v4(),
    addedToMyList: false,
    isVisibleToSlider: false,
    isLeftMostSlide: false,
    isRightMostSlide: false,
  },
  {
    title: 'The Apartment',
    duration: '125 minutes',
    year: 1960,
    genre: ['OSCAR WINNERS THAT ARE ACTUALLY GOOD'],
    director: 'Billy Wilder',
    actors: ['Jack Lemmon, Shirley MacLaine, Fred MacMurray'],
    img: theApartment,
    id: uuid.v4(),
    addedToMyList: false,
    isVisibleToSlider: false,
    isLeftMostSlide: false,
    isRightMostSlide: false,
  },
  {
    title: 'Amadeus',
    duration: '160 minutes',
    year: 1984,
    genre: ['OSCAR WINNERS THAT ARE ACTUALLY GOOD'],
    director: 'Milos Forman',
    actors: ['F. Murray Abraham, Tom Hulce, Elizabeth Berridge'],
    img: amadeus,
    id: uuid.v4(),
    addedToMyList: false,
    isVisibleToSlider: false,
    isLeftMostSlide: false,
    isRightMostSlide: false,
  },
  {
    title: 'From Here To Eternity',
    duration: '118 minutes',
    year: 1953,
    genre: ['OSCAR WINNERS THAT ARE ACTUALLY GOOD'],
    director: 'Fred Zinnemann',
    actors: ['Burt Lancaster, Montgomery Clift, Deborah Kerr'],
    img: fromHereToEternity,
    id: uuid.v4(),
    addedToMyList: false,
    isVisibleToSlider: false,
    isLeftMostSlide: false,
    isRightMostSlide: false,
  },
  {
    title: 'Annie Hall',
    duration: '93 minutes',
    year: 1977,
    director: 'Woody Allen',
    genre: ['OSCAR WINNERS THAT ARE ACTUALLY GOOD'],
    actors: ['Woody Allen, Diane Keaton, Tony Roberts'],
    img: annieHall,
    id: uuid.v4(),
    addedToMyList: false,
    isVisibleToSlider: false,
    isLeftMostSlide: false,
    isRightMostSlide: false,
  },
  {
    title: 'Frances Ha',
    duration: '86 minutes',
    year: 2012,
    genre: ['DIRECTED BY NOAH BAUMBACH'],
    director: 'Noah Baumbach',
    actors: ['Greta Gerwig, Mickey Sumner, Adam Driver'],
    img: francesHa,
    id: uuid.v4(),
    addedToMyList: false,
    isVisibleToSlider: false,
    isLeftMostSlide: false,
    isRightMostSlide: false,
  },
  {
    title: 'Mistress America',
    duration: '84 minutes',
    year: 2015,
    genre: ['DIRECTED BY NOAH BAUMBACH'],
    director: 'Noah Baumbach',
    actors: ['Greta Gerwig, Lola Kirke, Shana Dowdeswell'],
    img: mistressAmerica,
    id: uuid.v4(),
    addedToMyList: false,
    isVisibleToSlider: false,
    isLeftMostSlide: false,
    isRightMostSlide: false,
  },
  {
    title: 'Kicking and Screaming',
    duration: '96 minutes',
    year: 1995,
    genre: ['DIRECTED BY NOAH BAUMBACH'],
    director: 'Noah Baumbach',
    actors: ['Josh Hamilton, Eric Stoltz, Samuel Gould'],
    img: kickingAndScreaming,
    id: uuid.v4(),
    addedToMyList: false,
    isVisibleToSlider: false,
    isLeftMostSlide: false,
    isRightMostSlide: false,
  },
  {
    title: 'Greenberg',
    duration: '107 minutes',
    year: 2010,
    genre: ['DIRECTED BY NOAH BAUMBACH'],
    director: 'Noah Baumbach',
    actors: ['Ben Stiller, Greta Gerwig, Jennifer Jason Leigh'],
    img: greenberg,
    id: uuid.v4(),
    addedToMyList: false,
    isVisibleToSlider: false,
    isLeftMostSlide: false,
    isRightMostSlide: false,
  },
  {
    title: 'The Squid and the Whale',
    duration: '81 minutes',
    year: 2005,
    genre: ['I GUESS THIS IS GROWING UP', 'DIRECTED BY NOAH BAUMBACH'],
    director: 'Noah Baumbach',
    actors: ['Owen Kline, Jeff Daniels, Laura Linney'],
    img: squidAndTheWhale,
    id: uuid.v4(),
    addedToMyList: false,
    isVisibleToSlider: false,
    isLeftMostSlide: false,
    isRightMostSlide: false,
  },
  {
    title: 'Margot at the Wedding',
    duration: '91 minutes',
    year: 2007,
    genre: ['DIRECTED BY NOAH BAUMBACH'],
    director: 'Noah Baumbach',
    actors: ['Nicole Kidman, Jennifer Jason Leigh, Flora Cross'],
    img: margotAtTheWedding,
    id: uuid.v4(),
    addedToMyList: false,
    isVisibleToSlider: false,
    isLeftMostSlide: false,
    isRightMostSlide: false,
  },
  {
    title: 'The Meyerowitz Stories (New and Selected)',
    duration: '112 minutes',
    year: 2017,
    genre: ['DIRECTED BY NOAH BAUMBACH'],
    director: 'Noah Baumbach',
    actors: ['Adam Sandler, Grace Van Patten, Dustin Hoffman'],
    img: theMeyerowitzStories,
    id: uuid.v4(),
    addedToMyList: false,
    isVisibleToSlider: false,
    isLeftMostSlide: false,
    isRightMostSlide: false,
  },
  {
    title: 'While We Were Young',
    duration: '97 minutes',
    year: 2014,
    genre: ['DIRECTED BY NOAH BAUMBACH'],
    director: 'Noah Baumbach',
    actors: ['Ben Stiller, Naomi Watts, Adam Driver'],
    img: whileWeWereYoung,
    id: uuid.v4(),
    addedToMyList: false,
    isVisibleToSlider: false,
    isLeftMostSlide: false,
    isRightMostSlide: false,
  },
  {
    title: 'Apocalypse Now',
    duration: '147 minutes',
    year: 1979,
    genre: ["FAVORITE PALME D'OR WINNERS"],
    director: 'Francis Ford Coppola',
    actors: ['Martin Sheen, Marlon Brando, Robert Duvall'],
    img: apocalypseNow,
    id: uuid.v4(),
    addedToMyList: false,
    isVisibleToSlider: false,
    isLeftMostSlide: false,
    isRightMostSlide: false,
  },
  {
    title: 'All That Jazz',
    duration: '123 minutes',
    year: 1979,
    genre: ["FAVORITE PALME D'OR WINNERS"],
    director: 'Bob Fosse',
    actors: ['Roy Scheider, Jessica Lange, Leland Palmer'],
    img: allThatJazz,
    id: uuid.v4(),
    addedToMyList: false,
    isVisibleToSlider: false,
    isLeftMostSlide: false,
    isRightMostSlide: false,
  },
  {
    title: 'Pulp Fiction',
    duration: '154 minutes',
    year: 1994,
    genre: ["FAVORITE PALME D'OR WINNERS"],
    director: 'Quentin Tarantino',
    actors: [' John Travolta, Uma Thurman, Samuel L. Jackson'],
    img: pulpFiction,
    id: uuid.v4(),
    addedToMyList: false,
    isVisibleToSlider: false,
    isLeftMostSlide: false,
    isRightMostSlide: false,
  },
  {
    title: 'Miss Julie',
    duration: '90 minutes',
    year: 1951,
    genre: ["FAVORITE PALME D'OR WINNERS"],
    director: 'Alf Sjöberg',
    actors: ['Anita Björk, Ulf Palme, Märta Dorff'],
    img: missJulie,
    id: uuid.v4(),
    addedToMyList: false,
    isVisibleToSlider: false,
    isLeftMostSlide: false,
    isRightMostSlide: false,
  },
  {
    title: 'The Conversation',
    duration: '113 minutes',
    year: 1974,
    genre: ["FAVORITE PALME D'OR WINNERS"],
    director: 'Francis Ford Coppola',
    actors: ['Gene Hackman, John Cazale, Allen Garfield'],
    img: theConversation,
    id: uuid.v4(),
    addedToMyList: false,
    isVisibleToSlider: false,
    isLeftMostSlide: false,
    isRightMostSlide: false,
  },
  {
    title: 'Wages of Fear',
    duration: '131 minutes',
    year: 1953,
    genre: ["FAVORITE PALME D'OR WINNERS"],
    director: 'Henri-Georges Clouzot',
    actors: ['Yves Montand, Charles Vanel, Peter van Eyck'],
    img: wagesOfFear,
    id: uuid.v4(),
    addedToMyList: false,
    isVisibleToSlider: false,
    isLeftMostSlide: false,
    isRightMostSlide: false,
  },
  {
    title: 'If....',
    duration: '111 minutes',
    year: 1968,
    genre: ["FAVORITE PALME D'OR WINNERS"],
    director: 'Lindsay Anderson',
    actors: [' Malcolm McDowell, David Wood, Richard Warwick '],
    img: ifEllipsis,
    id: uuid.v4(),
    addedToMyList: false,
    isVisibleToSlider: false,
    isLeftMostSlide: false,
    isRightMostSlide: false,
  },
  {
    title: 'Kagemusha',
    duration: '97 minutes',
    year: 2014,
    genre: ["FAVORITE PALME D'OR WINNERS"],
    director: 'Akira Kurosawa ',
    actors: ["Tatsuya Nakadai, Tsutomu Yamazaki, Ken'ichi Hagiwara"],
    img: kagemusha,
    id: uuid.v4(),
    addedToMyList: false,
    isVisibleToSlider: false,
    isLeftMostSlide: false,
    isRightMostSlide: false,
  },
  {
    title: 'Paris Texas',
    duration: '145 minutes',
    year: 1984,
    genre: ["FAVORITE PALME D'OR WINNERS"],
    director: 'Wim Wenders',
    actors: ['Harry Dean Stanton, Nastassja Kinski, Dean Stockwell'],
    img: parisTexas,
    id: uuid.v4(),
    addedToMyList: false,
    isVisibleToSlider: false,
    isLeftMostSlide: false,
    isRightMostSlide: false,
  },
  {
    title: 'Dancer in the Dark',
    duration: '140 minutes',
    year: 2000,
    genre: ["FAVORITE PALME D'OR WINNERS"],
    director: 'Lars von Trier',
    actors: ['Björk, Catherine Deneuve, David Morse'],
    img: dancerInTheDark,
    id: uuid.v4(),
    addedToMyList: false,
    isVisibleToSlider: false,
    isLeftMostSlide: false,
    isRightMostSlide: false,
  },
  {
    title: 'Taxi Driver',
    duration: '114 minutes',
    year: 1976,
    genre: ['SCORSESE AND DE NIRO', "FAVORITE PALME D'OR WINNERS"],
    director: 'Martin Scorsese',
    actors: ['Robert De Niro, Jodie Foster, Cybill Shepherd'],
    img: taxiDriver,
    id: uuid.v4(),
    addedToMyList: false,
    isVisibleToSlider: false,
    isLeftMostSlide: false,
    isRightMostSlide: false,
  },
  {
    title: 'Casino',
    duration: '178 minutes',
    year: 1995,
    genre: ['SCORSESE AND DE NIRO'],
    director: 'Martin Scorsese',
    actors: ['Robert De Niro, Sharon Stone, Joe Pesci'],
    img: casino,
    id: uuid.v4(),
    addedToMyList: false,
    isVisibleToSlider: false,
    isLeftMostSlide: false,
    isRightMostSlide: false,
  },
  {
    title: 'Mean Streets',
    duration: '112 minutes',
    year: 1973,
    genre: ['SCORSESE AND DE NIRO'],
    director: 'Martin Scorsese',
    actors: ['Robert De Niro, Harvey Keitel, David Proval'],
    img: meanStreets,
    id: uuid.v4(),
    addedToMyList: false,
    isVisibleToSlider: false,
    isLeftMostSlide: false,
    isRightMostSlide: false,
  },
  {
    title: 'King of Comedy',
    duration: '109 minutes',
    year: 1982,
    genre: ['SCORSESE AND DE NIRO'],
    director: 'Martin Scorsese',
    actors: ['Robert De Niro, Jerry Lewis, Diahnne Abbott'],
    img: kingOfComedy,
    id: uuid.v4(),
    addedToMyList: false,
    isVisibleToSlider: false,
    isLeftMostSlide: false,
    isRightMostSlide: false,
  },
  {
    title: 'New York, New York',
    duration: '155 minutes',
    year: 1977,
    genre: ['SCORSESE AND DE NIRO'],
    director: 'Martin Scorsese',
    actors: ['Liza Minnelli, Robert De Niro, Lionel Stander'],
    img: newYorkNewYork,
    id: uuid.v4(),
    addedToMyList: false,
    isVisibleToSlider: false,
    isLeftMostSlide: false,
    isRightMostSlide: false,
  },
  {
    title: 'Goodfellas',
    duration: '97 minutes',
    year: 1990,
    genre: ['SCORSESE AND DE NIRO'],
    director: 'Martin Scorsese',
    actors: ['Robert De Niro, Ray Liotta, Joe Pesci'],
    img: goodfellas,
    id: uuid.v4(),
    addedToMyList: false,
    isVisibleToSlider: false,
    isLeftMostSlide: false,
    isRightMostSlide: false,
  },
  {
    title: 'There Will Be Blood',
    duration: '158 minutes',
    year: 2007,
    genre: ['FILMS OF THE WEEK'],
    director: 'Paul Thomas Anderson',
    actors: ['Daniel Day-Lewis, Paul Dano, Ciarán Hinds'],
    img: thereWillBeBlood,
    id: uuid.v4(),
    addedToMyList: false,
    isVisibleToSlider: false,
    isLeftMostSlide: false,
    isRightMostSlide: false,
  },
  {
    title: 'Fish Tank',
    duration: '123 minutes',
    year: 2009,
    genre: ['FILMS OF THE WEEK'],
    director: 'Andrea Arnold',
    actors: ['Katie Jarvis, Michael Fassbender, Kierston Wareing'],
    img: fishTank,
    id: uuid.v4(),
    addedToMyList: false,
    isVisibleToSlider: false,
    isLeftMostSlide: false,
    isRightMostSlide: false,
  },
];

export default filmData;
